export const dummyGuestlist = [
  { name: "Myron", surname: "Ellison", circle: "wolfach", attending: "yes" },
  { name: "Elvia", surname: "Fletcher", circle: "wolfach", attending: "maybe" },
  { name: "Louella", surname: "Galloway", circle: "freiburg", attending: null },
  {
    name: "Johnathon",
    surname: "Delgado",
    circle: "freiburg",
    attending: "no",
  },
  { name: "Harris", surname: "Hardin", circle: "utrecht", attending: "yes" },
  { name: "Stanford", surname: "Ferrell", circle: "utrecht", attending: "no" },
  { name: "Brendan", surname: "Spence", circle: "budapest", attending: null },
  { name: "Angelia", surname: "Dalton", circle: "budapest", attending: "no" },
  { name: "Tonino", surname: "Redonet", circle: "valencia", attending: "yes" },
  { name: "Wilburn", surname: "Heath", circle: "valencia", attending: "no" },
  { name: "Sydney", surname: "Ritter", circle: "valencia", attending: "yes" },
  { name: "Brett", surname: "Crane", circle: "valencia", attending: "no" },
  { name: "Bradley", surname: "Hancock", circle: "bolt", attending: "yes" },
  { name: "Margarita", surname: "Robbins", circle: "bolt", attending: "no" },
  { name: "Ezra", surname: "George", circle: "nagua", attending: null },
  { name: "Garfield", surname: "Mcbride", circle: "nagua", attending: "no" },
  { name: "Dave", surname: "Hicks", circle: "gigtor", attending: "yes" },
  { name: "Mattie", surname: "Rich", circle: "gigtor", attending: "no" },
  { name: "Rich", surname: "Boyle", circle: "+1", attending: null },
  { name: "Ezekiel", surname: "Logan", circle: "+1", attending: "yes" },
];
