version: "2"
services:
  rafafest:
    build: ../
    container_name: rafafest
    environment:
      JWT_SECRET: CHANGE_ME
      MONGO_CONNECTION_STRING: CHANGE_ME
    networks:
      - proxy
    depends_on:
      - mongo
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rafafest.entrypoints=http"
      - "traefik.http.routers.rafafest.rule=Host(`rafafest.com`)"
      - "traefik.http.middlewares.rafafest-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.rafafest.middlewares=rafafest-https-redirect"
      - "traefik.http.routers.rafafest-secure.entrypoints=https"
      - "traefik.http.routers.rafafest-secure.rule=Host(`rafafest.com`)"
      - "traefik.http.routers.rafafest-secure.tls=true"
      - "traefik.http.routers.rafafest-secure.service=rafafest"
      - "traefik.http.services.rafafest.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
  mongo:
      image: mongo:4.0
      container_name: rafafest_db
      ports:
          - 27017:27017
      environment:
          MONGO_INITDB_ROOT_USERNAME: CHANGE_ME
          MONGO_INITDB_ROOT_PASSWORD: CHANGE_ME
          MONGO_INITDB_DATABASE: rafafest
      networks:
        - proxy
      volumes:
          - ../data/db:/data/db

networks:
  proxy:
    external: true
